// complement = what goes mid-clause at the end but before any separable
// particle (e.g. "eine Freundin", "in die Schule", "zu Mittag"). An empty
// complement means there is none.
// particle = separable prefix that drops to the very end of the clause
// in a main clause ("auf", "an", "fern"). Empty when the verb is not
// separable.
window.TAGESABLAUF_DATA = [
  {
    inf: "auf/stehen",
    fr: "se lever",
    complement: "",
    particle: "auf",
    ich: "stehe",
    du: "stehst",
    er: "steht",
    sie: "steht",
    wir: "stehen",
  },
  {
    inf: "frühstücken",
    fr: "prendre le petit-déjeuner",
    complement: "",
    particle: "",
    ich: "frühstücke",
    du: "frühstückst",
    er: "frühstückt",
    sie: "frühstückt",
    wir: "frühstücken",
  },
  {
    inf: "in die Schule gehen",
    fr: "aller à l'école",
    complement: "in die Schule",
    particle: "",
    ich: "gehe",
    du: "gehst",
    er: "geht",
    sie: "geht",
    wir: "gehen",
  },
  {
    inf: "zu Mittag essen",
    fr: "déjeuner",
    complement: "zu Mittag",
    particle: "",
    ich: "esse",
    du: "isst",
    er: "isst",
    sie: "isst",
    wir: "essen",
  },
  {
    inf: "nach Hause gehen",
    fr: "rentrer à la maison",
    complement: "nach Hause",
    particle: "",
    ich: "gehe",
    du: "gehst",
    er: "geht",
    sie: "geht",
    wir: "gehen",
  },
  {
    inf: "eine Freundin an/rufen",
    fr: "appeler une amie",
    complement: "eine Freundin",
    particle: "an",
    ich: "rufe",
    du: "rufst",
    er: "ruft",
    sie: "ruft",
    wir: "rufen",
  },
  {
    inf: "zu Abend essen",
    fr: "dîner",
    complement: "zu Abend",
    particle: "",
    ich: "esse",
    du: "isst",
    er: "isst",
    sie: "isst",
    wir: "essen",
  },
  {
    inf: "fern/sehen",
    fr: "regarder la télé",
    complement: "",
    particle: "fern",
    ich: "sehe",
    du: "siehst",
    er: "sieht",
    sie: "sieht",
    wir: "sehen",
  },
  {
    inf: "schlafen gehen",
    fr: "aller se coucher",
    complement: "schlafen",
    particle: "",
    ich: "gehe",
    du: "gehst",
    er: "geht",
    sie: "geht",
    wir: "gehen",
  },
];
